//Scratch for dealing with events

const startSample = `
{
    "taskToken":"AAAAKgAAAAIAAAAAAAAAAot+4WGHv5pZfFkRn9tGM+pJ0QTH0q2apydTSEWCt7OR+Zrzqn8GfXPlBkQn0pw2r+fF6Jz+uC+nruPKralrwSECmozBQR0en2QWFyqhEnF9bx1OXHL9JHImcDQIHh4Vo1CLJqfSPrOez1u01GHQwQFTuTOKqo0L6/lW/M8TPgY7bvLU2Q7n3LrcJwpJ6e0IjADtPPm81EOh1nyYL0IEv8ychd4+6c4ZFEN/8IiOGp33bZmaKNx+Q0lvurZClFe5kYCyhq3kXOrk6iYNP7tEGi+pm1mJIb7GKxZd+EosJmgabqFQ64weFgA+ltBN8FxMWg==",
    "startedEventId":18,
    "workflowExecution":{
       "workflowId":"158e3482-bf0b-58af-8bbf-3d4b3381a8b2",
       "runId":"22m7RJq/1nFvC2aEnLFifMvU68L/fTIq2NXWnqsbeSmXI="
    },
    "workflowType":{
       "name":"Milestone Flow 1",
       "version":"v1"
    },
    "events":[
       {
          "eventTimestamp":"2018-11-02T15:52:25.986Z",
          "eventType":"WorkflowExecutionStarted",
          "eventId":1,
          "workflowExecutionStartedEventAttributes":{
             "input":"",
             "executionStartToCloseTimeout":"15552000",
             "taskStartToCloseTimeout":"60",
             "childPolicy":"REQUEST_CANCEL",
             "taskList":{
                "name":"msflow"
             },
             "workflowType":{
                "name":"Milestone Flow 1",
                "version":"v1"
             },
             "parentInitiatedEventId":0
          }
       },
       {
          "eventTimestamp":"2018-11-02T15:52:25.986Z",
          "eventType":"DecisionTaskScheduled",
          "eventId":2,
          "decisionTaskScheduledEventAttributes":{
             "taskList":{
                "name":"msflow"
             },
             "startToCloseTimeout":"60"
          }
       },
       {
          "eventTimestamp":"2018-11-02T15:52:35.638Z",
          "eventType":"DecisionTaskStarted",
          "eventId":3,
          "decisionTaskStartedEventAttributes":{
             "identity":"DqSMokNY",
             "scheduledEventId":2
          }
       },
       {
          "eventTimestamp":"2018-11-02T15:53:35.640Z",
          "eventType":"DecisionTaskTimedOut",
          "eventId":4,
          "decisionTaskTimedOutEventAttributes":{
             "timeoutType":"START_TO_CLOSE",
             "scheduledEventId":2,
             "startedEventId":3
          }
       },
       {
          "eventTimestamp":"2018-11-02T15:53:35.640Z",
          "eventType":"DecisionTaskScheduled",
          "eventId":5,
          "decisionTaskScheduledEventAttributes":{
             "taskList":{
                "name":"msflow"
             },
             "startToCloseTimeout":"60"
          }
       },
       {
          "eventTimestamp":"2018-11-02T15:53:35.671Z",
          "eventType":"DecisionTaskStarted",
          "eventId":6,
          "decisionTaskStartedEventAttributes":{
             "identity":"DqSMokNY",
             "scheduledEventId":5
          }
       },
       {
          "eventTimestamp":"2018-11-02T15:54:35.673Z",
          "eventType":"DecisionTaskTimedOut",
          "eventId":7,
          "decisionTaskTimedOutEventAttributes":{
             "timeoutType":"START_TO_CLOSE",
             "scheduledEventId":5,
             "startedEventId":6
          }
       },
       {
          "eventTimestamp":"2018-11-02T15:54:35.673Z",
          "eventType":"DecisionTaskScheduled",
          "eventId":8,
          "decisionTaskScheduledEventAttributes":{
             "taskList":{
                "name":"msflow"
             },
             "startToCloseTimeout":"60"
          }
       },
       {
          "eventTimestamp":"2018-11-02T15:54:35.717Z",
          "eventType":"DecisionTaskStarted",
          "eventId":9,
          "decisionTaskStartedEventAttributes":{
             "identity":"DqSMokNY",
             "scheduledEventId":8
          }
       },
       {
          "eventTimestamp":"2018-11-02T15:55:35.719Z",
          "eventType":"DecisionTaskTimedOut",
          "eventId":10,
          "decisionTaskTimedOutEventAttributes":{
             "timeoutType":"START_TO_CLOSE",
             "scheduledEventId":8,
             "startedEventId":9
          }
       },
       {
          "eventTimestamp":"2018-11-02T15:55:35.719Z",
          "eventType":"DecisionTaskScheduled",
          "eventId":11,
          "decisionTaskScheduledEventAttributes":{
             "taskList":{
                "name":"msflow"
             },
             "startToCloseTimeout":"60"
          }
       },
       {
          "eventTimestamp":"2018-11-02T15:55:35.784Z",
          "eventType":"DecisionTaskStarted",
          "eventId":12,
          "decisionTaskStartedEventAttributes":{
             "identity":"DqSMokNY",
             "scheduledEventId":11
          }
       },
       {
          "eventTimestamp":"2018-11-02T15:56:35.786Z",
          "eventType":"DecisionTaskTimedOut",
          "eventId":13,
          "decisionTaskTimedOutEventAttributes":{
             "timeoutType":"START_TO_CLOSE",
             "scheduledEventId":11,
             "startedEventId":12
          }
       },
       {
          "eventTimestamp":"2018-11-02T15:56:35.786Z",
          "eventType":"DecisionTaskScheduled",
          "eventId":14,
          "decisionTaskScheduledEventAttributes":{
             "taskList":{
                "name":"msflow"
             },
             "startToCloseTimeout":"60"
          }
       },
       {
          "eventTimestamp":"2018-11-02T15:56:35.833Z",
          "eventType":"DecisionTaskStarted",
          "eventId":15,
          "decisionTaskStartedEventAttributes":{
             "identity":"DqSMokNY",
             "scheduledEventId":14
          }
       },
       {
          "eventTimestamp":"2018-11-02T15:57:35.835Z",
          "eventType":"DecisionTaskTimedOut",
          "eventId":16,
          "decisionTaskTimedOutEventAttributes":{
             "timeoutType":"START_TO_CLOSE",
             "scheduledEventId":14,
             "startedEventId":15
          }
       },
       {
          "eventTimestamp":"2018-11-02T15:57:35.835Z",
          "eventType":"DecisionTaskScheduled",
          "eventId":17,
          "decisionTaskScheduledEventAttributes":{
             "taskList":{
                "name":"msflow"
             },
             "startToCloseTimeout":"60"
          }
       },
       {
          "eventTimestamp":"2018-11-02T15:57:35.871Z",
          "eventType":"DecisionTaskStarted",
          "eventId":18,
          "decisionTaskStartedEventAttributes":{
             "identity":"DqSMokNY",
             "scheduledEventId":17
          }
       }
    ],
    "previousStartedEventId":0
 }
`

const _ = require('lodash');

let sample = JSON.parse(startSample);
let events = sample.events;

console.log(events);

let filtered = _.filter(events, (o) => { return o.eventType != 'DecisionTaskStarted'
                         && o.eventType != 'DecisionTaskScheduled'
                        && o.eventType != 'DecisionTaskTimedOut' });

console.log('filter...');
console.log(filtered);