service: decider

provider:
  name: aws
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'swf:StartWorkflowExecution'
      Resource: '*'
  stage: ${opt:stage, 'dev'}
  runtime: nodejs8.10

functions:
  start:
    handler: decider.handler
    environment:
      STATE_MACHINE_ARN: "arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:statemachine:process1-${opt:stage, self:provider.stage}"
      WORKFLOW_TYPE: 'Milestone Flow 1'
      WORKFLOW_DOMAIN: 'e2e'
      WORKFLOW_VERSION: 'v1'
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true


plugins:
  - serverless-pseudo-parameters