service: milestones

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs8.10
  environment:
    WORKFLOW_DOMAIN: 'e2e'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'swf:SignalWorkflowExecution'
      Resource: '*'
  apiKeys:
    - milestones-${opt:stage, self:provider.stage}
  usagePlan:
    throttle:
      burstLimit: 10
      rateLimit: 5

functions:
  step1:
    handler: steps.step1
  step3:
    handler: steps.step3

stepFunctions:

  stateMachines:
    milestones:
      name: milestones-${opt:stage}
      definition:
          StartAt: m1
          States:
            m1:
              Type: Task
              Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-step1"
              ResultPath: '$.step1'
              Next: m2
            m2:
              Type: Pass
              Next: m3
            m3:
              Type: Task
              Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-step3"
              ResultPath: '$.step3'
              End: true




plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
