service: milestones

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs8.10
  apiKeys:
    - milestones-${opt:stage, self:provider.stage}
  usagePlan:
    throttle:
      burstLimit: 10
      rateLimit: 5

functions:
  step3:
    handler: steps.step3

stepFunctions:

  stateMachines:
    milestones:
      name: milestones-${opt:stage}
      events:
        - http:
            path: create
            method: POST
            private: true
      definition:
          StartAt: m1
          States:
            m1:
              Type: Pass
              Next: m2
            m2:
              Type: Pass
              Next: m3
            m3:
              Type: Task
              Resource: "arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:${self:service}-${opt:stage}-step3"
              ResultPath: '$.step3'
              End: true




plugins:
  - serverless-step-functions
  - serverless-pseudo-parameters
