service: start

provider:
  name: aws
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'swf:StartWorkflowExecution'
      Resource: '*'
  stage: ${opt:stage, 'dev'}
  runtime: nodejs8.10
  apiKeys:
    - start-${opt:stage, self:provider.stage}
  usagePlan:
    throttle:
      burstLimit: 10
      rateLimit: 5

functions:
  start:
    handler: start.handler
    events:
      - http:
          path: create
          method: POST
          private: true
    environment:
      STATE_MACHINE_ARN: "arn:aws:states:#{AWS::Region}:#{AWS::AccountId}:statemachine:process1-${opt:stage, self:provider.stage}"
      WORKFLOW_TYPE: 'Milestone Flow 1'
      WORKFLOW_DOMAIN: 'e2e'
      WORKFLOW_VERSION: 'v1'


plugins:
  - serverless-pseudo-parameters